number = input('Enter number of fruits:\n')
fruits = str(input('Enter name of fruit:\n'))
print('______________________________________________\n')
print('{:^12}'.format(''), 'I have', number, ',', fruits)
print('______________________________________________\n')